accessControl:
  salt: NLscyh9j3ToL7crFrj3Q8Na4askDoALB
api:
  key: 9FAB4A6619844132BB0880D3E3B7DF83
appearance: {}
feature: {}
gcodeViewer: {}
plugins:
  GPX: {}
  announcements:
    channels:
      _important:
        read_until: 1460575175
      _news:
        read_until: 1472994000
      _octopi:
        read_until: 1462200600
      _releases:
        read_until: 1476703800
  cost:
    currency: £
  discovery:
    upnpUuid: 53175380-6f00-419e-8b83-f5b7ba36bf47
  softwareupdate:
    _config_version: 4
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint/
        prerelease: false
        type: github_release
printerParameters: {}
printerProfiles:
  default: ff_creator_pro
  defaultProfile: {}
serial:
  baudrate: 115200
  maxCommunicationTimeouts: {}
  port: /dev/ttyACM0
  timeout: {}
server:
  commands: {}
  firstRun: false
  secretKey: 6jAxqT4MhM9SNjQdmgKNt19f2O9u96jb
system:
  actions:
  - action: streamon
    command: /home/pi/scripts/webcam start
    confirm: false
    name: Start video stream
  - action: streamoff
    command: /home/pi/scripts/webcam stop
    confirm: false
    name: Stop video stream
  - action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system.
    name: Reboot
temperature: {}
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: http://192.168.0.108:8080/?action=stream
